added description of the github variables that need to be set and made the BASE_DOMAIN variable required

diff --git a/.github/workflows/deploy-main.yml b/.github/workflows/deploy-main.yml
--- a/.github/workflows/deploy-main.yml
+++ b/.github/workflows/deploy-main.yml
@@ -111,7 +111,8 @@ jobs:
         BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}
       run: |
         if [[ -z "${BASE_DOMAIN}" ]]; then
-          BASE_DOMAIN="dragonbytes.org"
+          echo "BASE_DOMAIN GitHub variable is required." >&2
+          exit 1
         fi
 
         kubectl apply -f kube/namespace.yml
